### PR TITLE
Fix TabView not correctly initialized

### PR DESCRIPTION
**Pull request by huyphams**
Hi @robin

I noted that the tabview init not correctly:
```
LYTabView(0x608000141d90) - NSView not correctly initialized. Did you forget to call super?
```
So I fixed the init function, remove redundant code too
Huy.

### CODE REVIEW

**Comment by robin** [comment]
How can I reproduce the issue?

**Comment by huyphams** [comment]
Hi @robin 
This is example project.
- Project is completely empty but tabview.
- Because View of tab View was not initialed => Add image => Crash.
- In my main project have some flag so it logged out the view not initialed correctly.
[EmptyProject.zip](https://github.com/robin/LYTabView/files/995014/EmptyProject.zip)

It's fixed on my PR and also remove some duplicated init function.

**Comment by robin** [comment]
I think the problem is we should not use the coder to init the subviews in LYTabView but we still need the init to call setupViews. I applied a fix in master branch. Can you have a look? Thanks.

**Comment by huyphams** [comment]
Yeah, thank you

**Pull request closed without merging**
